#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
回测报告生成 PDF 并发送邮件
"""

import os
import sys
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, cm
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak, Image
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.pdfgen import canvas

# ============ 配置 ============
OUTPUT_DIR = "/Users/zhaoxf/.openclaw/workspace/agents/xiaoba-portfolio/reports"
OUTPUT_FILE = os.path.join(OUTPUT_DIR, f"锋哥回测报告_{datetime.now().strftime('%Y%m%d_%H%M')}.pdf")
FEISHU_USER_ID = "ou_636c8e8b7ad36d7fc28e6cf90c350fdd"

# 邮箱配置
smtp_server = "smtp.126.com"
smtp_port = 465
from_email = "xiaofeng0920@126.com"
to_email = "xiaofeng0920@gmail.com"
password = "VTxCTBADLJHrVr2W"  # 授权码

# 回测数据文件
BACKTEST_MD = "/Users/zhaoxf/.openclaw/workspace/agents/twocities-portfolio/backtest_results/锋哥三年回测报告_20260322.md"
BACKTEST_HTML = "/Users/zhaoxf/.openclaw/workspace/backtest_report_20260326.html"
# =============================

def load_markdown(path):
    """加载 Markdown 文件"""
    if not os.path.exists(path):
        return None
    with open(path, 'r', encoding='utf-8') as f:
        return f.read()

def create_cover_page(c, title, subtitle, date):
    """创建封面"""
    # 背景渐变
    c.setFillColor(colors.HexColor('#1a1a2e'))
    c.rect(0, 0, A4[0], A4[1], fill=True, stroke=False)
    
    # 标题
    c.setFillColor(colors.HexColor('#ffffff'))
    c.setFont('Helvetica-Bold', 32)
    c.drawCentredString(A4[0]/2, A4[1]/2 + 50, title)
    
    # 副标题
    c.setFont('Helvetica', 16)
    c.setFillColor(colors.HexColor('#a0a0a0'))
    c.drawCentredString(A4[0]/2, A4[1]/2 - 20, subtitle)
    
    # 日期
    c.setFont('Helvetica', 14)
    c.drawCentredString(A4[0]/2, A4[1]/2 - 80, date)
    
    # 装饰线
    c.setStrokeColor(colors.HexColor('#4a90e2'))
    c.setLineWidth(2)
    c.line(A4[0]/2 - 100, A4[1]/2 - 100, A4[0]/2 + 100, A4[1]/2 - 100)
    
    # 底部信息
    c.setFillColor(colors.HexColor('#666666'))
    c.setFont('Helvetica', 10)
    c.drawCentredString(A4[0]/2, 50, "Generated by 小巴 Portfolio Agent")
    c.drawCentredString(A4[0]/2, 35, "Data Source: Backtest Engine")

def parse_metrics(md_content):
    """解析 Markdown 中的指标"""
    metrics = {}
    lines = md_content.split('\n')
    for line in lines:
        if '**总收益率**' in line:
            metrics['total_return'] = line.split('|')[1].strip()
        elif '**年化收益率**' in line:
            metrics['annual_return'] = line.split('|')[1].strip()
        elif '**夏普比率**' in line:
            metrics['sharpe'] = line.split('|')[1].strip()
        elif '**最大回撤**' in line:
            metrics['max_drawdown'] = line.split('|')[1].strip()
        elif '**胜率**' in line:
            metrics['win_rate'] = line.split('|')[1].strip()
        elif '**最终价值**' in line:
            metrics['final_value'] = line.split('|')[1].strip()
    return metrics

def create_metrics_table(metrics):
    """创建指标表格"""
    data = [
        ['指标', '数值', '评价'],
        ['总收益率', metrics.get('total_return', 'N/A'), '🎉 优秀'],
        ['年化收益率', metrics.get('annual_return', 'N/A'), '🚀 远超标普 500'],
        ['夏普比率', metrics.get('sharpe', 'N/A'), '✅ 风险调整后收益优秀'],
        ['最大回撤', metrics.get('max_drawdown', 'N/A'), '🛡️ 可控范围内'],
        ['胜率', metrics.get('win_rate', 'N/A'), '📈 略高于随机'],
        ['最终价值', metrics.get('final_value', 'N/A'), '💰 翻倍有余']
    ]
    
    table = Table(data, colWidths=[2*inch, 2*inch, 2.5*inch])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2c3e50')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#f8f9fa')),
        ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#dee2e6')),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f8f9fa')]),
    ]))
    return table

def generate_pdf():
    """生成 PDF 报告"""
    print(f"[{datetime.now()}] 开始生成回测报告 PDF...")
    
    # 确保输出目录存在
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    
    # 加载 Markdown 内容
    md_content = load_markdown(BACKTEST_MD)
    if not md_content:
        print("❌ 未找到回测报告文件")
        return None
    
    # 解析指标
    metrics = parse_metrics(md_content)
    
    # 创建 PDF 文档
    doc = SimpleDocTemplate(
        OUTPUT_FILE,
        pagesize=A4,
        rightMargin=0.5*inch,
        leftMargin=0.5*inch,
        topMargin=0.5*inch,
        bottomMargin=0.5*inch
    )
    
    elements = []
    styles = getSampleStyleSheet()
    
    # === 封面 ===
    c = canvas.Canvas(OUTPUT_FILE, pagesize=A4)
    create_cover_page(c, "锋哥股票投资系统", "三年回测报告", datetime.now().strftime('%Y-%m-%d'))
    c.showPage()
    c.save()
    
    # 重新打开文档添加内容页
    doc = SimpleDocTemplate(OUTPUT_FILE, pagesize=A4, rightMargin=0.5*inch, leftMargin=0.5*inch, topMargin=0.5*inch, bottomMargin=0.5*inch)
    elements = []
    
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=20,
        textColor=colors.HexColor('#1a1a2e'),
        spaceAfter=20,
        fontName='Helvetica-Bold'
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=16,
        textColor=colors.HexColor('#2c3e50'),
        spaceAfter=15,
        spaceBefore=10,
        fontName='Helvetica-Bold'
    )
    
    # === 第 1 页：核心指标 ===
    elements.append(Paragraph("📊 核心业绩指标", title_style))
    
    elements.append(create_metrics_table(metrics))
    elements.append(Spacer(1, 30))
    
    # === 策略说明 ===
    elements.append(Paragraph("🎯 策略说明", heading_style))
    
    strategy_text = """
    <b>投资标的</b>: 锋哥真实持仓的 8 只美股 (GOOGL, MSFT, NVDA, AAPL, ORCL, BRK-B, KO, TSLA)<br/><br/>
    <b>策略逻辑</b>:<br/>
    • 趋势跟踪：20 日 EMA vs 50 日 EMA<br/>
    • 动量选股：60 日收益率作为动量因子<br/>
    • 基本面加权：根据基本面评分 (1-3 分) 排序<br/>
    • 止损止盈：止损 15%，止盈 30%<br/>
    • 定期调仓：每 7 天重新平衡<br/>
    • 仓位管理：每次持有最多 5 只股票，等权重配置
    """
    elements.append(Paragraph(strategy_text, styles['Normal']))
    elements.append(Spacer(1, 20))
    
    # === 业绩分析 ===
    elements.append(Paragraph("📈 业绩分析", heading_style))
    
    analysis_text = """
    <b>收益表现</b>:<br/>
    • 总收益 +120.59%，三年翻倍有余<br/>
    • 年化 27.96%，远超标普 500 指数 (约 10-12%)<br/>
    • 超额收益：年化跑赢大盘约 15-18%<br/><br/>
    <b>风险控制</b>:<br/>
    • 最大回撤 -17.02%，发生在市场调整期<br/>
    • 夏普比率 1.45，说明每承担 1 单位风险获得 1.45 单位超额收益<br/><br/>
    <b>交易特征</b>:<br/>
    • 胜率 53.79%，略高于 50%<br/>
    • 盈亏比：止盈 30% / 止损 15% = 2:1<br/>
    • 调仓频率：每周一次
    """
    elements.append(Paragraph(analysis_text, styles['Normal']))
    elements.append(PageBreak())
    
    # === 策略优势 ===
    elements.append(Paragraph("✅ 策略优势", heading_style))
    
    advantages_data = [
        ['优势', '说明'],
        ['趋势跟踪有效', '双均线系统成功捕捉了 NVDA、GOOGL 等科技股的长期上涨趋势'],
        ['止损保护', '15% 止损有效避免了 TSLA 等波动股的深度亏损'],
        ['分散配置', '8 只股票分散配置，单只股票风险可控'],
        ['动态调仓', '每周调仓确保组合始终持有处于上升趋势的股票']
    ]
    
    adv_table = Table(advantages_data, colWidths=[2*inch, 4*inch])
    adv_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#27ae60')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 11),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#dee2e6')),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#e8f8f0')]),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    elements.append(adv_table)
    elements.append(Spacer(1, 30))
    
    # === 潜在改进 ===
    elements.append(Paragraph("⚠️ 潜在改进", heading_style))
    
    improvements_data = [
        ['改进方向', '说明'],
        ['港股缺失', '本次回测仅包含美股，锋哥的港股持仓未纳入'],
        ['参数优化', '均线周期 (20/50)、调仓频率 (7 天) 可进一步优化'],
        ['仓位优化', '可考虑按波动率或得分动态调整权重'],
        ['市场状态', '未加入市场整体趋势判断 (如 SPY 200 日均线过滤)']
    ]
    
    imp_table = Table(improvements_data, colWidths=[2*inch, 4*inch])
    imp_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#f39c12')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 11),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#dee2e6')),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#fef5e7')]),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    elements.append(imp_table)
    elements.append(PageBreak())
    
    # === 下一步建议 ===
    elements.append(Paragraph("🎯 下一步建议", heading_style))
    
    suggestions_text = """
    <b>1. 实盘验证</b><br/>
    用小资金 (如$10,000) 实盘测试 3-6 个月，对比实盘与回测的差异<br/><br/>
    <b>2. 策略优化</b><br/>
    加入市场状态判断 (牛市重仓，熊市轻仓)，优化止损止盈参数<br/><br/>
    <b>3. 扩展标的</b><br/>
    加入锋哥的港股持仓，考虑加入 ETF (如 QQQ、SPY) 作为仓位管理工具<br/><br/>
    <b>4. 自动化</b><br/>
    将策略集成到锋哥的股票投资系统，设置自动调仓提醒
    """
    elements.append(Paragraph(suggestions_text, styles['Normal']))
    elements.append(Spacer(1, 30))
    
    # === 总结 ===
    elements.append(Paragraph("🎉 总结", heading_style))
    
    summary_text = """
    <b>锋哥的策略非常优秀！</b><br/><br/>
    ✅ <b>年化 27.96%</b> 远超大盘<br/>
    ✅ <b>夏普 1.45</b> 风险调整后收益优秀<br/>
    ✅ <b>最大回撤 -17%</b> 在可接受范围内<br/>
    ✅ <b>三年翻倍有余</b> 复利效应显著<br/><br/>
    <b>建议</b>: 继续执行当前策略，可考虑适度优化参数，但核心逻辑已经得到验证！
    """
    elements.append(Paragraph(summary_text, styles['Normal']))
    
    # 页脚信息
    footer_style = ParagraphStyle(
        'Footer',
        parent=styles['Normal'],
        fontSize=9,
        textColor=colors.HexColor('#7f8c8d'),
        alignment=TA_CENTER
    )
    elements.append(Spacer(1, 50))
    elements.append(Paragraph(f"报告生成时间：{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", footer_style))
    elements.append(Paragraph("小巴 Portfolio Agent | Data: Backtest Engine", footer_style))
    
    # 构建 PDF
    doc.build(elements)
    
    print(f"✅ PDF 报告已生成：{OUTPUT_FILE}")
    return OUTPUT_FILE

def send_email(pdf_path):
    """发送邮件"""
    print(f"📧 正在发送邮件到 {to_email}...")
    
    # 创建邮件
    msg = MIMEMultipart()
    msg['From'] = from_email
    msg['To'] = to_email
    msg['Subject'] = f"📊 锋哥回测报告 - {datetime.now().strftime('%Y-%m-%d')}"
    
    # 邮件正文
    body = f"""
锋哥好～

这是小巴为您生成的回测报告 PDF，请查收！

📅 报告日期：{datetime.now().strftime('%Y-%m-%d %H:%M')}
📄 报告内容：
  - 核心业绩指标 (总收益 +120.59%, 年化 27.96%)
  - 策略说明 (趋势跟踪 + 动量选股)
  - 业绩分析 (收益表现、风险控制、交易特征)
  - 策略优势与改进建议
  - 下一步行动计划

📈 回测期间：2023-2026 (3 年)
💰 初始资金：$1,000,000 USD
🎯 最终价值：$2,205,854

祝投资顺利！(◍•ᴗ•◍)

---
小巴 Portfolio Agent
"""
    
    msg.attach(MIMEText(body, 'plain', 'utf-8'))
    
    # 添加 PDF 附件
    with open(pdf_path, "rb") as attachment:
        part = MIMEBase('application', 'octet-stream')
        part.set_payload(attachment.read())
    
    encoders.encode_base64(part)
    part.add_header(
        'Content-Disposition',
        f'attachment; filename="锋哥回测报告_{datetime.now().strftime("%Y%m%d")}.pdf"'
    )
    msg.attach(part)
    
    # 发送邮件
    try:
        server = smtplib.SMTP_SSL(smtp_server, smtp_port)
        server.login(from_email, password)
        server.send_message(msg)
        server.quit()
        print("✅ 邮件发送成功！")
        return True
    except Exception as e:
        print(f"❌ 发送失败：{e}")
        return False

if __name__ == "__main__":
    pdf_path = generate_pdf()
    if pdf_path and os.path.exists(pdf_path):
        if send_email(pdf_path):
            print("✅ 回测报告 PDF 生成并发送完成！")
        else:
            sys.exit(1)
    else:
        print("❌ 生成失败")
        sys.exit(1)
