#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
锋哥持仓报告 - PDF 版本
生成专业的持仓分析报告（含图表 + 表格）
数据源：富途 OpenD + 持仓配置文件
"""

import json
import os
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, cm
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image, PageBreak
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.pdfgen import canvas
import matplotlib
matplotlib.use('Agg')  # 非交互式后端
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
from futu import *

# ============ 配置 ============
CONFIG_FILE = "/Users/zhaoxf/.openclaw/workspace/agents/xiaoba-portfolio/config/feng_portfolio.json"
OUTPUT_DIR = "/Users/zhaoxf/.openclaw/workspace/agents/xiaoba-portfolio/reports"
OUTPUT_FILE = os.path.join(OUTPUT_DIR, f"锋哥持仓报告_{datetime.now().strftime('%Y%m%d_%H%M')}.pdf")
FEISHU_USER_ID = "ou_636c8e8b7ad36d7fc28e6cf90c350fdd"
# =============================

# 中文字体配置
def get_chinese_font():
    """获取中文字体"""
    font_paths = [
        "/System/Library/Fonts/PingFang.ttc",
        "/System/Library/Fonts/Supplemental/PingFang.ttc",
        "/Library/Fonts/PingFang.ttc",
        "/System/Library/Fonts/STHeiti Light.ttc",
        "/System/Library/Fonts/STHeiti Medium.ttc",
    ]
    for path in font_paths:
        if os.path.exists(path):
            return path
    return None

CHINESE_FONT = get_chinese_font()

def register_fonts():
    """注册中文字体"""
    if CHINESE_FONT:
        fm.fontManager.addfont(CHINESE_FONT)
        plt.rcParams['font.sans-serif'] = ['PingFang SC', 'Heiti SC', 'sans-serif']
    plt.rcParams['axes.unicode_minus'] = False

register_fonts()

def load_portfolio():
    """加载持仓配置"""
    with open(CONFIG_FILE, 'r', encoding='utf-8') as f:
        return json.load(f)

def get_realtime_price(quote_ctx, symbol, market):
    """获取实时价格"""
    try:
        if market == 'US':
            code = f"US.{symbol}"
        else:
            code = f"HK.{symbol}"
        
        ret, data = quote_ctx.get_market_snapshot(code)
        if ret == RET_OK and len(data) > 0:
            return float(data['last_price'][0])
        return None
    except Exception as e:
        print(f"获取 {symbol} 价格失败：{e}")
        return None

def create_pie_chart(data, title, filename):
    """创建饼图"""
    plt.figure(figsize=(10, 6))
    
    labels = [item['label'] for item in data]
    sizes = [abs(item['value']) for item in data]
    colors_list = ['#2ecc71' if item['value'] >= 0 else '#e74c3c' for item in data]
    
    plt.pie(sizes, labels=labels, colors=colors_list, autopct='%1.1f%%', startangle=90)
    plt.title(title, fontsize=14, fontweight='bold')
    plt.axis('equal')
    
    plt.savefig(filename, dpi=150, bbox_inches='tight')
    plt.close()
    return filename

def create_bar_chart(data, title, filename, xlabel='', ylabel='盈亏 (%)'):
    """创建柱状图"""
    plt.figure(figsize=(12, 6))
    
    labels = [item['label'] for item in data]
    values = [item['value'] for item in data]
    colors_list = ['#2ecc71' if v >= 0 else '#e74c3c' for v in values]
    
    x_pos = range(len(labels))
    plt.bar(x_pos, values, color=colors_list)
    plt.xticks(x_pos, labels, rotation=45, ha='right')
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.title(title, fontsize=14, fontweight='bold')
    plt.axhline(y=0, color='black', linestyle='-', linewidth=0.5)
    plt.grid(axis='y', alpha=0.3)
    
    plt.savefig(filename, dpi=150, bbox_inches='tight')
    plt.close()
    return filename

def create_cover_page(c):
    """创建封面"""
    # 背景渐变
    c.setFillColor(colors.HexColor('#1a1a2e'))
    c.rect(0, 0, A4[0], A4[1], fill=True, stroke=False)
    
    # 标题
    c.setFillColor(colors.HexColor('#ffffff'))
    c.setFont('Helvetica-Bold', 36)
    c.drawCentredString(A4[0]/2, A4[1]/2 + 50, "锋哥持仓报告")
    
    # 副标题
    c.setFont('Helvetica', 18)
    c.setFillColor(colors.HexColor('#a0a0a0'))
    c.drawCentredString(A4[0]/2, A4[1]/2 - 20, "Portfolio Analysis Report")
    
    # 日期
    c.setFont('Helvetica', 14)
    c.drawCentredString(A4[0]/2, A4[1]/2 - 80, datetime.now().strftime('%Y年%m月%d日 %H:%M'))
    
    # 装饰线
    c.setStrokeColor(colors.HexColor('#4a90e2'))
    c.setLineWidth(2)
    c.line(A4[0]/2 - 100, A4[1]/2 - 100, A4[0]/2 + 100, A4[1]/2 - 100)
    
    # 底部信息
    c.setFillColor(colors.HexColor('#666666'))
    c.setFont('Helvetica', 10)
    c.drawCentredString(A4[0]/2, 50, "Generated by 小巴 Portfolio Agent")
    c.drawCentredString(A4[0]/2, 35, "Data Source: Futu OpenD")

def create_summary_table(portfolio, realtime_data=None):
    """创建总结表格"""
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=18,
        textColor=colors.HexColor('#1a1a2e'),
        spaceAfter=20,
        fontName='Helvetica-Bold'
    )
    
    elements = []
    
    # 标题
    elements.append(Paragraph("📊 总资产概览", title_style))
    
    # 计算总和
    us_value = portfolio['accounts']['us_stocks']['value_usd']
    hk_value_hkd = portfolio['accounts']['hk_stocks'].get('value_hkd', 440000 * 7.8)
    hk_value_usd = hk_value_hkd / 7.8
    margin_value = portfolio['accounts']['margin']['value_usd']
    
    total_value = us_value + hk_value_usd + margin_value
    total_pnl = portfolio['total_pnl_usd']
    total_pnl_pct = portfolio['total_pnl_percent']
    
    # 总结数据表格
    summary_data = [
        ['账户类型', '市值', '盈亏金额', '盈亏比例', '状态'],
        ['🇺🇸 美股账户', f'${us_value:,.0f}', f'{us_value * portfolio["accounts"]["us_stocks"]["pnl_percent"]/100:+,.0f} USD', 
         f'{portfolio["accounts"]["us_stocks"]["pnl_percent"]:+.2f}%', portfolio['accounts']['us_stocks']['status']],
        ['🇭🇰 港股账户', f'${hk_value_usd:,.0f}', f'{portfolio["accounts"]["hk_stocks"]["pnl_usd"]:+,.0f} USD', 
         f'{portfolio["accounts"]["hk_stocks"]["pnl_percent"]:+.2f}%', portfolio['accounts']['hk_stocks']['status']],
        ['💰 保证金账户', f'${margin_value:,.0f}', f'{portfolio["accounts"]["margin"]["pnl_usd"]:+,.0f} USD', 
         f'{portfolio["accounts"]["margin"]["pnl_percent"]:+.2f}%', portfolio['accounts']['margin']['status']],
        ['📈 总计', f'${total_value:,.0f}', f'{total_pnl:+,.0f} USD', f'{total_pnl_pct:+.2f}%', 
         '盈利' if total_pnl >= 0 else '亏损']
    ]
    
    summary_table = Table(summary_data, colWidths=[1.5*inch, 1.3*inch, 1.3*inch, 1*inch, 1*inch])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1a1a2e')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#f8f9fa')),
        ('BACKGROUND', (0, 4), (-1, 4), colors.HexColor('#e8f4f8')),
        ('TEXTCOLOR', (2, 4), (2, 4), colors.green if total_pnl >= 0 else colors.red),
        ('TEXTCOLOR', (3, 4), (3, 4), colors.green if total_pnl >= 0 else colors.red),
        ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#dee2e6')),
        ('ROWBACKGROUNDS', (0, 1), (-1, -2), [colors.white, colors.HexColor('#f8f9fa')]),
    ]))
    
    elements.append(summary_table)
    elements.append(Spacer(1, 30))
    
    return elements

def create_holdings_table(holdings, market='US'):
    """创建持仓明细表格"""
    is_hkd = market == 'HK'
    currency = 'HKD' if is_hkd else 'USD'
    
    # 表格数据
    table_data = [['股票', '股数', '成本价', '现价', '市值', '盈亏', '盈亏%', '建议']]
    
    for holding in holdings[:10]:  # 最多显示 10 只
        name = holding.get('name', holding['symbol'])
        symbol = holding['symbol']
        shares = holding['shares']
        avg_cost = holding[f'avg_cost_{currency.lower()}']
        current_price = holding[f'current_price_{currency.lower()}']
        value = holding[f'value_{currency.lower()}']
        pnl = holding[f'pnl_{currency.lower()}']
        pnl_pct = holding['pnl_percent']
        suggestion = holding.get('suggestion', '持有')
        
        table_data.append([
            f'{name}\n{symbol}',
            f'{shares:,}',
            f'{avg_cost:.2f}',
            f'{current_price:.2f}',
            f'{value:,.0f}',
            f'{pnl:+,.0f}',
            f'{pnl_pct:+.1f}%',
            suggestion
        ])
    
    # 创建表格
    col_widths = [1.5*inch, 0.8*inch, 0.9*inch, 0.9*inch, 1*inch, 0.9*inch, 0.8*inch, 1.2*inch]
    table = Table(table_data, colWidths=col_widths)
    
    # 样式
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2c3e50')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 10),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#bdc3c7')),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#ecf0f1')]),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('FONTSIZE', (0, 1), (-1, -1), 8),
    ]))
    
    # 盈亏颜色
    for i, holding in enumerate(holdings[:10], start=1):
        pnl_color = colors.green if holding['pnl_percent'] >= 0 else colors.red
        table.setStyle(TableStyle([
            ('TEXTCOLOR', (5, i), (5, i), pnl_color),
            ('TEXTCOLOR', (6, i), (6, i), pnl_color),
        ]))
    
    return table

def create_options_table(options, market='US'):
    """创建期权持仓表格"""
    is_hkd = market == 'HK'
    currency = 'HKD' if is_hkd else 'USD'
    
    table_data = [['标的', '类型', '到期日', '行权价', '数量', '成本', '现价', '盈亏', '状态']]
    
    for opt in options[:15]:  # 最多显示 15 个
        opt_type = 'CALL' if opt['type'] == 'CALL' else 'PUT'
        qty = opt['quantity']
        qty_str = f'{abs(qty)} {"Short" if qty < 0 else "Long"}'
        
        # 字段名处理
        avg_cost_key = f'avg_cost_{currency.lower()}' if is_hkd else 'avg_cost'
        current_price_key = f'current_price_{currency.lower()}' if is_hkd else 'current_price'
        
        avg_cost = opt.get(avg_cost_key, opt.get('avg_cost', 0))
        current_price = opt.get(current_price_key, opt.get('current_price', 0))
        pnl = opt.get(f'pnl_{currency.lower()}', opt.get('pnl_usd', opt.get('pnl_hkd', 0)))
        
        table_data.append([
            opt['symbol'],
            opt_type,
            opt['expiry'],
            f'{opt["strike"]:.0f}',
            qty_str,
            f'{avg_cost:.2f}',
            f'{current_price:.2f}',
            f'{pnl:+,.0f}',
            opt['status']
        ])
    
    col_widths = [1*inch, 0.6*inch, 0.9*inch, 0.8*inch, 0.9*inch, 0.7*inch, 0.7*inch, 0.8*inch, 0.8*inch]
    table = Table(table_data, colWidths=col_widths)
    
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#8e44ad')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 9),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#bdc3c7')),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f5eef8')]),
        ('FONTSIZE', (0, 1), (-1, -1), 7),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    
    # 状态颜色
    for i, opt in enumerate(options[:15], start=1):
        status_color = colors.green if opt['status'] == '盈利' else colors.red
        table.setStyle(TableStyle([('TEXTCOLOR', (8, i), (8, i), status_color)]))
    
    return table

def create_action_items_table(action_items):
    """创建行动项表格"""
    table_data = [['优先级', '行动', '目标', '建议', '影响']]
    
    for item in action_items[:10]:
        priority = item['priority']
        action = item['action']
        target = item['target']
        suggestion = item['suggestion']
        pnl = item.get('pnl_usd', item.get('pnl_hkd', 0))
        pnl_str = f'{pnl:+,.0f}'
        
        table_data.append([
            f'P{priority}',
            action,
            target,
            suggestion,
            pnl_str
        ])
    
    col_widths = [0.7*inch, 1.5*inch, 1.5*inch, 2*inch, 1*inch]
    table = Table(table_data, colWidths=col_widths)
    
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#e67e22')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 10),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#bdc3c7')),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#fef5e7')]),
        ('FONTSIZE', (0, 1), (-1, -1), 8),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    
    return table

def generate_pdf():
    """生成 PDF 报告"""
    print(f"[{datetime.now()}] 开始生成 PDF 报告...")
    
    # 确保输出目录存在
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    
    # 连接 OpenD 获取实时价格
    quote_ctx = OpenQuoteContext(host='127.0.0.1', port=11111)
    ret, state = quote_ctx.get_global_state()
    
    if ret != RET_OK or not state['qot_logined']:
        print("⚠️ OpenD 连接失败，使用缓存价格")
        quote_ctx = None
    
    # 加载持仓
    portfolio = load_portfolio()
    
    # 创建 PDF 文档
    doc = SimpleDocTemplate(
        OUTPUT_FILE,
        pagesize=A4,
        rightMargin=0.5*inch,
        leftMargin=0.5*inch,
        topMargin=0.5*inch,
        bottomMargin=0.5*inch
    )
    
    elements = []
    styles = getSampleStyleSheet()
    
    # === 封面 ===
    # 注意：封面需要用 canvas 直接绘制
    c = canvas.Canvas(OUTPUT_FILE, pagesize=A4)
    create_cover_page(c)
    c.showPage()
    c.save()
    
    # 重新打开文档添加内容页
    doc = SimpleDocTemplate(OUTPUT_FILE, pagesize=A4, rightMargin=0.5*inch, leftMargin=0.5*inch, topMargin=0.5*inch, bottomMargin=0.5*inch)
    elements = []
    
    # === 第 1 页：总结 ===
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=20,
        textColor=colors.HexColor('#1a1a2e'),
        spaceAfter=20,
        fontName='Helvetica-Bold'
    )
    
    elements.append(Paragraph("📊 总资产概览", title_style))
    
    # 计算总和
    us_value = portfolio['accounts']['us_stocks']['value_usd']
    hk_value_hkd = portfolio['accounts']['hk_stocks'].get('value_hkd', 440000 * 7.8)
    hk_value_usd = hk_value_hkd / 7.8
    margin_value = portfolio['accounts']['margin']['value_usd']
    
    total_value = us_value + hk_value_usd + margin_value
    total_pnl = portfolio['total_pnl_usd']
    total_pnl_pct = portfolio['total_pnl_percent']
    
    # 关键指标
    kpi_data = [
        ['总市值', '总盈亏', '盈亏比例', '账户数'],
        [f'${total_value:,.0f}', f'{total_pnl:+,.0f} USD', f'{total_pnl_pct:+.2f}%', '3']
    ]
    kpi_table = Table(kpi_data, colWidths=[2*inch, 2*inch, 2*inch, 1*inch])
    kpi_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#3498db')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 14),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 15),
        ('BACKGROUND', (0, 1), (-1, 1), colors.HexColor('#ebf5fb')),
        ('TEXTCOLOR', (1, 1), (1, 1), colors.green if total_pnl >= 0 else colors.red),
        ('TEXTCOLOR', (2, 1), (2, 1), colors.green if total_pnl >= 0 else colors.red),
    ]))
    elements.append(kpi_table)
    elements.append(Spacer(1, 30))
    
    # 账户明细
    elements.append(Paragraph("📈 账户明细", title_style))
    
    account_data = [
        ['账户', '市值', '盈亏金额', '盈亏%', '状态'],
        ['🇺🇸 美股', f'${us_value:,.0f} USD', 
         f'{us_value * portfolio["accounts"]["us_stocks"]["pnl_percent"]/100:+,.0f}', 
         f'{portfolio["accounts"]["us_stocks"]["pnl_percent"]:+.2f}%',
         portfolio['accounts']['us_stocks']['status']],
        ['🇭🇰 港股', f'${hk_value_usd:,.0f} USD', 
         f'{portfolio["accounts"]["hk_stocks"]["pnl_usd"]:+,.0f}', 
         f'{portfolio["accounts"]["hk_stocks"]["pnl_percent"]:+.2f}%',
         portfolio['accounts']['hk_stocks']['status']],
        ['💰 保证金', f'${margin_value:,.0f} USD', 
         f'{portfolio["accounts"]["margin"]["pnl_usd"]:+,.0f}', 
         f'{portfolio["accounts"]["margin"]["pnl_percent"]:+.2f}%',
         portfolio['accounts']['margin']['status']]
    ]
    
    account_table = Table(account_data, colWidths=[1.5*inch, 1.5*inch, 1.5*inch, 1*inch, 1*inch])
    account_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2c3e50')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 11),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#dee2e6')),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f8f9fa')]),
    ]))
    elements.append(account_table)
    elements.append(PageBreak())
    
    # === 第 2 页：美股持仓 ===
    elements.append(Paragraph("🇺🇸 美股持仓明细", title_style))
    us_table = create_holdings_table(portfolio['accounts']['us_stocks']['holdings'], 'US')
    elements.append(us_table)
    elements.append(Spacer(1, 30))
    
    # 美股期权
    if portfolio.get('options', {}).get('us_options'):
        elements.append(Paragraph("📑 美股期权", title_style))
        us_options_table = create_options_table(portfolio['options']['us_options'], 'US')
        elements.append(us_options_table)
    
    elements.append(PageBreak())
    
    # === 第 3 页：港股持仓 ===
    elements.append(Paragraph("🇭🇰 港股持仓明细", title_style))
    hk_table = create_holdings_table(portfolio['accounts']['hk_stocks']['holdings'], 'HK')
    elements.append(hk_table)
    elements.append(Spacer(1, 30))
    
    # 港股期权
    if portfolio.get('options', {}).get('hk_options'):
        elements.append(Paragraph("📑 港股期权", title_style))
        hk_options_table = create_options_table(portfolio['options']['hk_options'], 'HK')
        elements.append(hk_options_table)
    
    elements.append(PageBreak())
    
    # === 第 4 页：图表分析 ===
    elements.append(Paragraph("📊 盈亏分布分析", title_style))
    
    # 创建美股盈亏柱状图
    us_pnl_data = []
    for h in portfolio['accounts']['us_stocks']['holdings']:
        us_pnl_data.append({'label': h['symbol'], 'value': h['pnl_percent']})
    
    chart_path = os.path.join(OUTPUT_DIR, 'us_pnl_chart.png')
    create_bar_chart(us_pnl_data, "美股持仓盈亏分布", chart_path)
    
    if os.path.exists(chart_path):
        elements.append(Paragraph("🇺🇸 美股盈亏分布", styles['Heading3']))
        elements.append(Image(chart_path, width=6.5*inch, height=3.5*inch))
        elements.append(Spacer(1, 20))
    
    # 创建港股盈亏柱状图
    hk_pnl_data = []
    for h in portfolio['accounts']['hk_stocks']['holdings']:
        symbol = h['symbol'].replace('.HK', '')
        hk_pnl_data.append({'label': symbol, 'value': h['pnl_percent']})
    
    chart_path = os.path.join(OUTPUT_DIR, 'hk_pnl_chart.png')
    create_bar_chart(hk_pnl_data, "港股持仓盈亏分布", chart_path)
    
    if os.path.exists(chart_path):
        elements.append(Paragraph("🇭🇰 港股盈亏分布", styles['Heading3']))
        elements.append(Image(chart_path, width=6.5*inch, height=3.5*inch))
    
    elements.append(PageBreak())
    
    # === 第 5 页：行动建议 ===
    elements.append(Paragraph("🎯 行动建议", title_style))
    
    if portfolio.get('action_items'):
        action_table = create_action_items_table(portfolio['action_items'])
        elements.append(action_table)
    
    elements.append(Spacer(1, 30))
    
    # 亮点总结
    elements.append(Paragraph("✨ 投资亮点", title_style))
    highlights_style = ParagraphStyle(
        'Highlights',
        parent=styles['Normal'],
        fontSize=11,
        leftIndent=20,
        spaceAfter=10
    )
    
    for highlight in portfolio.get('highlights', []):
        elements.append(Paragraph(f"• {highlight}", highlights_style))
    
    # 页脚信息
    footer_style = ParagraphStyle(
        'Footer',
        parent=styles['Normal'],
        fontSize=9,
        textColor=colors.HexColor('#7f8c8d'),
        alignment=TA_CENTER
    )
    elements.append(Spacer(1, 50))
    elements.append(Paragraph(f"报告生成时间：{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", footer_style))
    elements.append(Paragraph("小巴 Portfolio Agent | Data: Futu OpenD", footer_style))
    
    # 构建 PDF
    doc.build(elements)
    
    if quote_ctx:
        quote_ctx.close()
    
    print(f"✅ PDF 报告已生成：{OUTPUT_FILE}")
    return OUTPUT_FILE

def send_pdf_to_feishu(pdf_path):
    """发送 PDF 到飞书"""
    import subprocess
    import base64
    
    # 读取 PDF 文件
    with open(pdf_path, 'rb') as f:
        pdf_data = base64.b64encode(f.read()).decode('utf-8')
    
    # 发送带附件的消息
    cmd = [
        "openclaw", "message", "send",
        "--channel", "feishu",
        "--target", FEISHU_USER_ID,
        "--message", f"📊 锋哥持仓报告已生成～\n\n生成时间：{datetime.now().strftime('%Y-%m-%d %H:%M')}\n\n请查收附件 PDF 文件 (◍•ᴗ•◍)",
        "--buffer", f"data:application/pdf;base64,{pdf_data}",
        "--filename", os.path.basename(pdf_path)
    ]
    
    try:
        subprocess.run(cmd, check=True)
        print("✅ PDF 已发送到飞书")
    except Exception as e:
        print(f"❌ 发送失败：{e}")

if __name__ == "__main__":
    pdf_path = generate_pdf()
    if pdf_path and os.path.exists(pdf_path):
        send_pdf_to_feishu(pdf_path)
        print("✅ 持仓报告 PDF 生成完成！")
    else:
        print("❌ 生成失败")
        sys.exit(1)
